In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\HP\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\HP\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('insurance_data.csv')

In [4]:
df

      age  gender     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   gender    1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [6]:
df[['region']]

         region
0     southwest
1     southeast
2     southeast
3     northwest
4     northwest
...         ...
1333  northwest
1334  northeast
1335  southeast
1336  southwest
1337  northwest

[1338 rows x 1 columns]

In [7]:
df

      age  gender     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [8]:
# df.head()/

In [9]:
# df.tail()

In [10]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1333    False
1334    False
1335    False
1336    False
1337    False
Length: 1338, dtype: bool

In [11]:
df.duplicated().sum()

np.int64(1)

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.isnull()

        age  gender    bmi  children  smoker  region  charges
0     False   False  False     False   False   False    False
1     False   False  False     False   False   False    False
2     False   False  False     False   False   False    False
3     False   False  False     False   False   False    False
4     False   False  False     False   False   False    False
...     ...     ...    ...       ...     ...     ...      ...
1333  False   False  False     False   False   False    False
1334  False   False  False     False   False   False    False
1335  False   False  False     False   False   False    False
1336  False   False  False     False   False   False    False
1337  False   False  False     False   False   False    False

[1337 rows x 7 columns]

In [15]:
df.isnull().sum()

age         0
gender      0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [16]:
df.dropna(inplace=True)

In [17]:
# df.isnull().sum()

In [18]:
df['region'].unique()

<StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

In [19]:
df['region'].nunique()

4

In [20]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    324
northeast    324
Name: count, dtype: int64

In [21]:
# df

In [22]:
df.drop(['smoker','children'],axis=1,inplace=True)

In [23]:
df

      age  gender     bmi     region      charges
0      19  female  27.900  southwest  16884.92400
1      18    male  33.770  southeast   1725.55230
2      28    male  33.000  southeast   4449.46200
3      33    male  22.705  northwest  21984.47061
4      32    male  28.880  northwest   3866.85520
...   ...     ...     ...        ...          ...
1333   50    male  30.970  northwest  10600.54830
1334   18  female  31.920  northeast   2205.98080
1335   18  female  36.850  southeast   1629.83350
1336   21  female  25.800  southwest   2007.94500
1337   61  female  29.070  northwest  29141.36030

[1337 rows x 5 columns]

In [24]:
df['region'].unique()

<StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

In [25]:
region_dict={
    'southwest':1, 'southeast':2, 'northwest':3, 'northeast':4
}

In [26]:
df['region']=df['region'].map(region_dict)

In [27]:
df

      age  gender     bmi  region      charges
0      19  female  27.900       1  16884.92400
1      18    male  33.770       2   1725.55230
2      28    male  33.000       2   4449.46200
3      33    male  22.705       3  21984.47061
4      32    male  28.880       3   3866.85520
...   ...     ...     ...     ...          ...
1333   50    male  30.970       3  10600.54830
1334   18  female  31.920       4   2205.98080
1335   18  female  36.850       2   1629.83350
1336   21  female  25.800       1   2007.94500
1337   61  female  29.070       3  29141.36030

[1337 rows x 5 columns]

In [28]:
char=df.select_dtypes(include='O')

C:\Users\HP\AppData\Local\Temp\ipykernel_10372\4005684811.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char=df.select_dtypes(include='O')

In [29]:
iint=df.select_dtypes(exclude="O")

In [30]:
char

      gender
0     female
1       male
2       male
3       male
4       male
...      ...
1333    male
1334  female
1335  female
1336  female
1337  female

[1337 rows x 1 columns]

In [31]:
iint

      age     bmi  region      charges
0      19  27.900       1  16884.92400
1      18  33.770       2   1725.55230
2      28  33.000       2   4449.46200
3      33  22.705       3  21984.47061
4      32  28.880       3   3866.85520
...   ...     ...     ...          ...
1333   50  30.970       3  10600.54830
1334   18  31.920       4   2205.98080
1335   18  36.850       2   1629.83350
1336   21  25.800       1   2007.94500
1337   61  29.070       3  29141.36030

[1337 rows x 4 columns]

In [32]:
df['gender'].unique()

<StringArray>
['female', 'male']
Length: 2, dtype: str

In [33]:
gender_dict={
    'female':0, 'male':1
}

In [34]:
df['gender']=df['gender'].map(gender_dict)

In [35]:
df

      age  gender     bmi  region      charges
0      19       0  27.900       1  16884.92400
1      18       1  33.770       2   1725.55230
2      28       1  33.000       2   4449.46200
3      33       1  22.705       3  21984.47061
4      32       1  28.880       3   3866.85520
...   ...     ...     ...     ...          ...
1333   50       1  30.970       3  10600.54830
1334   18       0  31.920       4   2205.98080
1335   18       0  36.850       2   1629.83350
1336   21       0  25.800       1   2007.94500
1337   61       0  29.070       3  29141.36030

[1337 rows x 5 columns]

In [36]:
x=df.drop('charges',axis=1)

In [37]:
x

      age  gender     bmi  region
0      19       0  27.900       1
1      18       1  33.770       2
2      28       1  33.000       2
3      33       1  22.705       3
4      32       1  28.880       3
...   ...     ...     ...     ...
1333   50       1  30.970       3
1334   18       0  31.920       4
1335   18       0  36.850       2
1336   21       0  25.800       1
1337   61       0  29.070       3

[1337 rows x 4 columns]

In [38]:
y=df[['charges']]

In [39]:
y

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1337 rows x 1 columns]

In [40]:
df.to_csv('clean insuranse.csv')

In [41]:
# pip install scikit-learn

In [42]:
import sklearn as sns

In [43]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train ,y_test =train_test_split(x , y , test_size=0.2, random_state= 42)

In [44]:
print(x_train.shape, x_test.shape , y_train.shape ,y_test.shape)

(1069, 4) (268, 4) (1069, 1) (268, 1)

In [45]:
x_train

      age  gender     bmi  region
1114   23       1  24.510       4
968    21       1  25.745       4
599    52       0  37.525       3
170    63       1  41.470       2
275    47       0  26.600       4
...   ...     ...     ...     ...
1096   51       0  34.960       4
1131   27       1  45.900       1
1295   20       1  22.000       1
861    38       0  28.000       1
1127   35       0  35.860       2

[1069 rows x 4 columns]

In [46]:
y_train

          charges
1114   2396.09590
968    3279.86855
599   33471.97189
170   13405.39030
275    9715.84100
...           ...
1096  44641.19740
1131   3693.42800
1295   1964.78000
861    7151.09200
1127   5836.52040

[1069 rows x 1 columns]

In [47]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [48]:
df

      age  gender     bmi  region      charges
0      19       0  27.900       1  16884.92400
1      18       1  33.770       2   1725.55230
2      28       1  33.000       2   4449.46200
3      33       1  22.705       3  21984.47061
4      32       1  28.880       3   3866.85520
...   ...     ...     ...     ...          ...
1333   50       1  30.970       3  10600.54830
1334   18       0  31.920       4   2205.98080
1335   18       0  36.850       2   1629.83350
1336   21       0  25.800       1   2007.94500
1337   61       0  29.070       3  29141.36030

[1337 rows x 5 columns]

In [49]:
lr.fit(x_train,y_train)

LinearRegression()

In [50]:
x_test

      age  gender     bmi  region
900    49       1  22.515       4
1064   29       0  25.600       1
1256   51       0  36.385       3
298    31       1  34.390       3
237    31       1  38.390       2
...   ...     ...     ...     ...
534    64       1  40.480       2
542    63       0  36.300       2
760    22       0  34.580       4
1284   61       1  36.300       1
1285   47       0  24.320       4

[268 rows x 4 columns]

In [51]:
pr=lr.predict(x_test)

In [52]:
lst=[49,1,22.515,4]

In [53]:
lr.predict([lst])

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[14075.20308208]])

In [54]:
pr

array([[14075.20308208],
       [ 8203.73335143],
       [16766.28005023],
       [13069.00009187],
       [13958.05349139],
       [17829.00442549],
       [10679.38499144],
       [ 6234.52802049],
       [14484.24795298],
       [15578.5717974 ],
       [14734.91371572],
       [15889.50509544],
       [13323.92587438],
       [20724.25792099],
       [13828.20177215],
       [14184.50767036],
       [ 9677.48625155],
       [14201.36366674],
       [ 8423.92586057],
       [ 9571.40610051],
       [ 8474.78878883],
       [12656.27302196],
       [17845.81963562],
       [12698.3629748 ],
       [12405.28908262],
       [ 9122.31148581],
       [15591.34604308],
       [18775.44526166],
       [14966.18192549],
       [17549.18041189],
       [10927.17691649],
       [17933.59033758],
       [ 6726.42954663],
       [17049.63180351],
       [20326.08489193],
       [15667.69650841],
       [ 6762.4528778 ],
       [ 7318.23073164],
       [14053.05729705],
       [13027.08291683],
       [11335.98518329],
       [10560.98031556],
       [16020.87377131],
       [17296.63828234],
       [10980.00984155],
       [ 8031.36092174],
       [10554.7012219 ],
       [12622.29851303],
       [ 8550.93462568],
       [14080.15791505],
       [10305.67834379],
       [17475.00974075],
       [12036.74929258],
       [10011.41460715],
       [15503.27523307],
       [14758.43157836],
       [16008.69444784],
       [ 6898.3931667 ],
       [13670.12418647],
       [14284.32550681],
       [17504.06260936],
       [12249.46373063],
       [15680.36524689],
       [ 8000.12825893],
       [18862.21784801],
       [13896.04662478],
       [15663.05091647],
       [13472.5858406 ],
       [ 7951.6727934 ],
       [19658.63589829],
       [11897.03023305],
       [ 7683.6597575 ],
       [12646.7959754 ],
       [ 4613.74048999],
       [17272.95734716],
       [ 3938.01464426],
       [21998.21098359],
       [13670.12418647],
       [11566.4487984 ],
       [18309.93466614],
       [ 9877.57132292],
       [19681.94957978],
       [20671.16502938],
       [15834.46084789],
       [17311.60942366],
       [17911.73010878],
       [10558.63744884],
       [ 8435.21467793],
       [12509.5072937 ],
       [10480.51644628],
       [19103.72474079],
       [ 8364.68509717],
       [ 9051.11454332],
       [ 9369.70418155],
       [ 6847.18602481],
       [18264.17177224],
       [19862.92674345],
       [12933.87645512],
       [10593.41227817],
       [13589.0729161 ],
       [17736.1656648 ],
       [18792.06510125],
       [13168.87671067],
       [18246.70342982],
       [12460.52902307],
       [ 6753.98805135],
       [11855.24996857],
       [ 7844.50753543],
       [16876.75993115],
       [11443.9856093 ],
       [11744.05268173],
       [15765.58857861],
       [12230.90025363],
       [12860.66828226],
       [11971.0934921 ],
       [11641.44225772],
       [ 6437.51954992],
       [ 9553.69221841],
       [13121.36619465],
       [12668.70605098],
       [17106.30700314],
       [14008.93384347],
       [16840.04255649],
       [13723.95190782],
       [12924.5538679 ],
       [14257.61627463],
       [ 8251.55343087],
       [16261.64551198],
       [12853.12625991],
       [19402.58422259],
       [16988.81542609],
       [16170.47804229],
       [ 9011.97195974],
       [14203.02065584],
       [12875.68097953],
       [ 8032.47787934],
       [15888.72009655],
       [10843.50583636],
       [ 7322.98093613],
       [ 9669.85295143],
       [10076.58099263],
       [ 9299.89200671],
       [17466.85472761],
       [16051.3061137 ],
       [11759.57847882],
       [12525.94082328],
       [15565.32224119],
       [12173.29453135],
       [15679.31211558],
       [19760.44709397],
       [12861.96727562],
       [11382.53307608],
       [12404.29460871],
       [20196.33306367],
       [12227.4081313 ],
       [ 8276.99641503],
       [16248.3870202 ],
       [19163.05204818],
       [14354.7322815 ],
       [16800.22303086],
       [16647.13116171],
       [ 8905.28762853],
       [16851.50338195],
       [17536.51135104],
       [16663.67823942],
       [15426.28828957],
       [17106.11163261],
       [ 6734.93483696],
       [ 7407.43669278],
       [ 7023.11772248],
       [10680.9375654 ],
       [ 9756.92035196],
       [ 9812.8543359 ],
       [14282.11386195],
       [13325.46070216],
       [ 7158.81336635],
       [ 6598.79885516],
       [14976.10869288],
       [12544.96173966],
       [16180.74008773],
       [19344.52833214],
       [ 9728.39857926],
       [15377.63713113],
       [14409.77652905],
       [13229.18470986],
       [16656.58516821],
       [11522.08951041],
       [10279.33668765],
       [ 5525.22600048],
       [13127.02400669],
       [12451.8833779 ],
       [13533.79218939],
       [16579.26294665],
       [10257.98968362],
       [ 6610.37322875],
       [ 8652.69642191],
       [14913.32596037],
       [ 8511.51542144],
       [15940.14080249],
       [20007.45402013],
       [ 9625.02951575],
       [ 7746.65560674],
       [11266.64092281],
       [17928.34994838],
       [ 9889.72760633],
       [11635.83429246],
       [13538.54239388],
       [14828.31619271],
       [ 8023.76840786],
       [15560.08185198],
       [11718.4782783 ],
       [14060.19115451],
       [10114.02503116],
       [11175.73641662],
       [15236.93737979],
       [ 9508.3697874 ],
       [ 9712.61907662],
       [17493.13243248],
       [15163.46107452],
       [ 7737.32408394],
       [ 8856.37350659],
       [18509.44894742],
       [17043.27069003],
       [17657.29451098],
       [16174.04701554],
       [20236.65126226],
       [16933.61627188],
       [11587.67254902],
       [10093.03698999],
       [ 9942.26526988],
       [21177.02579912],
       [12260.16656134],
       [10931.90408093],
       [15023.12073337],
       [14725.47745541],
       [13484.16066153],
       [13968.6416819 ],
       [ 9104.47512001],
       [10279.24573225],
       [ 8978.02897911],
       [10643.60752233],
       [10985.56840737],
       [11510.39143609],
       [13009.81843319],
       [ 7719.94592722],
       [12417.89399478],
       [ 6921.11160359],
       [14904.33093266],
       [ 7415.33812531],
       [14607.88707946],
       [ 8154.77799591],
       [15951.07053204],
       [17673.91435058],
       [17321.08647022],
       [17901.91733685],
       [ 6712.18442443],
       [14382.17679076],
       [10766.18393718],
       [12075.40169145],
       [17014.11276153],
       [10900.34507565],
       [20349.54709415],
       [18343.62406616],
       [22100.7804964 ],
       [19247.88476379],
       [ 9860.21620626],
       [19992.85983777],
       [12683.87243788]])

In [55]:
y_test

          charges
900    8688.85885
1064   5708.86700
1256  11436.73815
298   38746.35510
237    4463.20510
...           ...
534   13831.11520
542   13887.20400
760    3925.75820
1284  47403.88000
1285   8534.67180

[268 rows x 1 columns]

In [56]:
from sklearn.ensemble import RandomForestRegressor
rfg=RandomForestRegressor()

In [57]:
rfg.fit(x_train,y_train)

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [58]:
lst=[[49,1,22.515,4]]
rfg.predict(lst)

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([11907.1613985])

In [59]:
pr=rfg.predict(x_test)

In [60]:
pr

array([11907.1613985 ,  5871.6255753 , 15013.4329408 ,  8877.5829792 ,
       14686.2492247 , 14931.1193126 , 13388.8917511 ,  5982.507501  ,
       21422.4173821 , 11020.0640051 , 16162.657622  , 16887.8301004 ,
        8319.125912  , 25339.2388397 , 37026.4089394 , 12307.9477166 ,
       16606.9468485 , 21169.1723185 ,  3565.3054931 ,  9374.9911512 ,
        5993.091148  , 10675.2519821 , 20205.631649  ,  8466.8772607 ,
        8434.336115  ,  9744.4283798 , 10053.5296977 , 25581.4083416 ,
       16605.9330117 , 24751.2630503 ,  9483.7058606 , 20230.0952702 ,
        2172.2211656 , 12477.1662807 , 12438.509812  , 23058.0871885 ,
        4256.2174616 ,  9762.5918521 , 11868.4894822 , 12145.7719276 ,
       13434.4308406 , 15083.401226  , 25949.0554536 , 25440.2989317 ,
       10580.4423162 ,  4598.0903485 ,  3849.4765467 , 13946.1028039 ,
        4955.9912    , 10250.643789  ,  4958.2194372 , 24646.9543575 ,
        8786.68422   , 12843.4805245 , 24434.0191011 , 29955.7587944 ,
       13065.1180308 ,  7129.6305976 , 17949.5357223 , 13839.079415  ,
       14440.8925917 ,  6580.2123795 , 15984.30730533,  6839.0567687 ,
       10756.5339433 , 16383.8788132 , 23710.1710332 , 11979.0176239 ,
        3641.055215  , 29991.976938  , 12029.1354306 , 16015.9969349 ,
       10901.9573832 ,  8154.1635094 , 16917.9549684 ,  2446.7155178 ,
       27562.4252149 , 17949.5357223 , 11632.3568077 , 16361.3461657 ,
       13500.9255804 , 12627.8521529 , 34925.018756  , 28413.4816267 ,
       15969.8745705 , 16512.6633363 ,  9483.0767091 ,  6457.3570988 ,
       18394.9529847 , 13198.0601013 , 27975.7801301 ,  8923.0471703 ,
       10739.389065  , 10712.3562014 ,  3615.5038446 , 13482.6459814 ,
       35189.4092618 , 12265.6492768 ,  9795.7768338 , 10596.7039714 ,
       31215.4659068 , 12168.9929427 , 17389.1073828 , 10214.2458623 ,
        7953.8510111 ,  7315.5696708 ,  8549.5484988 ,  2547.3738645 ,
       15815.9191096 , 12629.9303496 , 13504.6650553 , 13750.8617378 ,
        9328.412523  , 14736.6436678 , 25336.7285225 , 15225.8353    ,
        3348.47600493,  6817.6110696 , 23686.108083  , 16795.7143392 ,
       14818.10296553,  8808.574459  , 33923.978602  ,  7547.59653613,
       10298.0284023 , 11794.6081119 ,  5044.5521813 , 19981.5153968 ,
       18226.5875722 , 16369.4022537 , 23170.8250956 , 18651.6640306 ,
        6234.1142512 , 11844.1817113 , 13568.3138    ,  6997.9298073 ,
       23427.7562308 , 12070.0570062 ,  9100.5562854 ,  6723.093301  ,
        9054.3499503 ,  8577.3348853 , 18669.9261087 , 12901.1899579 ,
       12827.6920147 , 10716.6050434 ,  7481.547709  ,  8588.0980067 ,
       21278.09881   , 32543.2621328 , 19170.7367485 , 10736.5029394 ,
        9269.2610941 , 19147.3764515 ,  9045.7501604 ,  7972.9215791 ,
       11875.7981843 , 11986.7962285 , 15957.57531   , 19088.960449  ,
       13129.1813874 ,  7991.1585439 , 15983.87198928, 14421.8543736 ,
       13134.34898273, 16067.3817673 , 14756.0328187 , 10858.0992911 ,
       10528.8689835 ,  4360.0886715 ,  7660.3213237 ,  4664.119054  ,
       11236.0527092 , 16631.4939917 , 26749.7311809 ,  9597.3148052 ,
        3125.1711649 , 19479.2472933 , 10006.7614602 , 24566.8380663 ,
       27674.4299441 , 11481.6779624 , 14239.1916897 , 16588.1897417 ,
        8218.9077832 , 15547.971596  , 19666.3314613 , 22817.9809405 ,
        8814.3827431 , 35565.1651241 , 15036.4718308 , 19232.2247948 ,
       16873.7037941 ,  5112.4946445 ,  4815.0289249 , 10834.5017869 ,
       11861.1780696 ,  7296.8743201 , 14749.0236079 , 16605.7398045 ,
        9521.3219601 ,  8422.1300062 ,  7435.377393  , 16910.1138757 ,
        7650.3879083 , 20835.5647641 ,  7596.32909   , 21174.8820307 ,
       14745.9479284 , 17768.01856677, 12151.9328514 , 13978.8532298 ,
       12933.19308   , 10021.2677025 , 16802.18642427,  5311.592962  ,
        5260.1653805 , 15370.5826928 , 14449.8617268 , 10761.3955869 ,
       16120.1829893 , 27447.5268326 , 15767.364489  , 26172.5153187 ,
       12900.9300332 , 23642.4268475 , 23147.3901746 , 11143.4441215 ,
        9531.0180015 , 13364.4394153 , 14425.4999753 ,  7470.5077939 ,
       10752.3677739 , 16587.3253557 , 18376.7693775 , 14539.6366029 ,
       17543.5824074 , 26949.1747295 ,  4606.3563688 ,  5434.7274525 ,
       21942.0500642 , 14487.8517795 , 10653.6908919 , 17552.6118442 ,
        5181.67351588, 14257.5883045 ,  5301.4003127 , 30353.0000623 ,
        9348.2308441 , 19117.1181261 ,  5999.2164376 , 11809.22804   ,
       13843.7440158 , 14581.3107433 , 15544.0742976 ,  6464.0593078 ,
       16476.8238022 , 13294.1921624 ,  8193.7475559 , 23754.7458926 ,
        8577.8724745 , 18001.7662899 , 25903.1186025 , 22823.8247065 ,
       19564.7699807 ,  5690.946498  , 28699.5315199 , 18121.7133796 ])

In [61]:
y_test

          charges
900    8688.85885
1064   5708.86700
1256  11436.73815
298   38746.35510
237    4463.20510
...           ...
534   13831.11520
542   13887.20400
760    3925.75820
1284  47403.88000
1285   8534.67180

[268 rows x 1 columns]

In [65]:
from sklearn.tree import DecisionTreeRegressor
dtc=DecisionTreeRegressor()

In [66]:
dtc.fit(x_train,y_train)

DecisionTreeRegressor()

In [67]:
dtc.score(x_train,y_train)

0.9955466255903963

In [68]:
dtc.score(x_test,y_test)

-0.7815799386777382

In [69]:
dtc.predict(x_test)

array([ 9361.3268 ,  4529.477  , 10848.1343 ,  4462.7218 ,  3875.7341 ,
        8125.7845 ,  2136.88225,  2731.9122 , 42211.1382 , 11735.87905,
       13616.3586 , 26109.32905,  4518.82625, 14235.072  , 40419.0191 ,
        7441.053  , 23082.95533, 36950.2567 ,  2302.3    ,  4350.5144 ,
        1880.487  ,  6548.19505, 47462.894  ,  5484.4673 ,  6128.79745,
        1880.487  ,  7650.77375, 46130.5265 , 40720.55105, 42111.6647 ,
       35595.5898 ,  8125.7845 ,  1121.8739 , 11743.299  ,  9748.9106 ,
       42856.838  ,  2331.519  ,  4134.08245, 11013.7119 ,  7742.1098 ,
        2026.9741 ,  8627.5411 , 42211.1382 ,  9174.13565,  7526.70645,
        3353.284  ,  2217.46915,  8520.026  ,  5312.16985,  4449.462  ,
        3171.6149 ,  6610.1097 , 21774.32215, 36124.5737 , 40103.89   ,
       41999.52   ,  9617.66245, 14426.07385,  4320.41085,  8162.71625,
       11093.6229 ,  6112.35295, 29186.48236, 16450.8947 ,  9391.346  ,
       12479.70895, 39871.7043 ,  6849.026  ,  1252.407  , 48517.56315,
        7526.70645, 21344.8467 ,  7173.35995,  2585.269  , 27218.43725,
        1727.785  , 12982.8747 ,  4320.41085,  8269.044  , 12730.9996 ,
        2459.7201 ,  9549.5651 , 12347.172  , 42211.1382 , 13457.9608 ,
       11743.299  ,  3558.62025,  1875.344  , 39611.7577 ,  2497.0383 ,
       46130.5265 ,  4134.08245,  3847.674  ,  1256.299  ,  2331.519  ,
        9866.30485, 47269.854  ,  7742.1098 ,  1826.843  ,  8603.8234 ,
       47305.305  , 10713.644  , 22218.1149 , 10085.846  ,  6112.35295,
       11884.04858,  4922.9159 ,  3279.86855, 12268.63225, 11737.84884,
       37270.1512 , 11082.5772 ,  6112.35295,  6334.34355, 38344.566  ,
        1534.3045 ,  1927.06445, 36124.5737 , 39611.7577 , 22218.1149 ,
       12265.5069 , 36950.2567 , 42560.4304 ,  3935.1799 ,  7421.19455,
       14358.36437,  1969.614  , 28868.6639 , 39611.7577 , 14210.53595,
       28868.6639 ,  8347.1643 ,  1815.8759 , 11015.1747 ,  3989.841  ,
        1622.1885 , 44202.6536 ,  8627.5411 ,  2257.47525, 10795.93733,
       20420.60465,  3385.39915,  8569.8618 , 11931.12525,  1149.3959 ,
        7954.517  ,  4686.3887 ,  7624.63   ,  8527.532  , 45710.20785,
       39836.519  ,  5855.9025 ,  4646.759  , 15170.069  ,  5415.6612 ,
        1748.774  ,  6196.448  ,  8083.9198 , 10338.9316 , 41919.097  ,
       12268.63225,  7133.9025 , 13430.265  , 12430.95335, 13430.265  ,
        8334.45755, 40974.1649 , 26125.67477,  2352.96845,  4005.4225 ,
        3736.4647 ,  1633.9618 , 20984.0936 , 22218.1149 , 39725.51805,
       16776.30405,  2102.2647 , 40974.1649 ,  7526.70645, 40720.55105,
       45710.20785,  2899.48935,  8442.667  , 10197.7722 ,  7954.517  ,
       26109.32905,  3277.161  , 34472.841  ,  2913.569  , 36837.467  ,
        3201.24515, 12479.70895, 29186.48236,  3972.9247 , 16450.8947 ,
        1720.3537 ,  6600.20595,  3554.203  , 14001.1338 , 13470.8044 ,
        2362.22905,  4529.477  ,  5478.0368 , 10807.4863 , 19350.3689 ,
       37079.372  ,  8538.28845,  6849.026  , 18033.9679 , 39871.7043 ,
        7624.63   , 24915.22085, 21472.4788 ,  6123.5688 , 13012.20865,
        1631.8212 ,  2166.732  ,  8342.90875, 30284.64294, 21344.8467 ,
       35147.52848, 47462.894  ,  8944.1151 , 26926.5144 , 11881.9696 ,
       15161.5344 , 41919.097  ,  7526.70645, 33732.6867 , 17361.7661 ,
       12982.8747 ,  5253.524  ,  3292.52985,  6082.405  , 22412.6485 ,
       21232.18226, 13012.20865, 36149.4835 ,  3987.926  ,  3981.9768 ,
       34779.615  ,  3292.52985, 18157.876  ,  9861.025  , 15518.18025,
       21098.55405,  2974.126  , 40103.89   , 17352.6803 , 24476.47851,
        2261.5688 , 11658.37915, 11743.299  , 13430.265  ,  9583.8933 ,
       14283.4594 , 22412.6485 ,  2459.7201 ,  7153.5539 , 41919.097  ,
        1646.4297 , 14474.675  , 11987.1682 , 15170.069  , 14313.8463 ,
        2020.5523 , 27941.28758, 21880.82   ])

In [70]:
from sklearn.tree import DecisionTreeClassifier
import joblib
dtc=DecisionTreeRegressor()
dtc.fit(x_train,y_train)

DecisionTreeRegressor()

In [72]:
joblib.dump(dtc,'cost-predictor')

['cost-predictor']

In [73]:
model=joblib.load('cost-predictor')